import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillMail } from "react-icons/ai";
import Image from "next/image";
import portrait from "../public/portrait.png";
import programming from "../public/programming.png";
import foodvisualizer from "../public/foodvisualizer.png";
import campers from "../public/campers.png";
import calc from "../public/calculator-app.png";
import quote from "../public/quote-generator.png";
import sql from "../public/sql-server.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Amanda&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lora&family=Poppins&display=swap"
          rel="stylesheet"
        />

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css"
        />
      </Head>
      <main className="bg-Rosewhite-400 px-10 dark:bg-gray-800 lg:px-40 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <div className="flex items-center">
              <Image src={programming} alt="logo" height={30} />

              <h1 className="text-xl font-burtons ml-2">Developed by Amanda</h1>
            </div>
            <ul className="flex items-center">
              <li>
                <a href="#">
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" text-2xl"
                  />
                </a>
              </li>
              <li>
                <a
                  className="font-lora bg-gradient-to-r from-pink to-blue text-whitesmoke px-4 py-2 rounded-md ml-8"
                  href="https://acrobat.adobe.com/link/track?uri=urn:aaid:scds:US:2bccd935-618a-3b1b-98c6-fead4d614f19"
                  target="_blank"
                  rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-blue font-medium md:text-6xl font-poppins">
              Hi, I&apos;m Amanda 👋
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-600 dark:text-whitesmoke font-poppins">
              Junior Frontend Developer
            </h3>
          </div>
          <div className="text-5xl flex justify-center gap-5 py-3 text-gray-600 dark:text-whitesmoke">
            <a
              href="https://www.linkedin.com/in/amandaroj/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://github.com/amandaroj"
              target="_blank"
              rel="noreferrer"
            >
              {" "}
              <AiFillGithub />
            </a>
            <a href="#contact">
              {" "}
              <AiFillMail />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-lightblue to-lightpink rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src={portrait}
              alt="profile image"
              layout="fill"
              objectFit="cover"
              overflow
            />
          </div>
        </section>

        <section>
          <div className="flex flex-col lg:flex-row lg:flex-wrap py-10 gap-10">
            <div className="basis-1/3 flex-1">
              <h3 className="text-center text-2xl py-2 md:text-3xl  dark:text-whitesmoke font-poppins">
                Tools I use
              </h3>
              <hr />
              <div className="flex justify-center">
                <div className="grid grid-cols-4 place-items-center m-w-1/2">
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-html5-plain-wordmark colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white  dark:bg-gray-200">
                    <i className="devicon-css3-plain-wordmark colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-javascript-plain colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-ruby-plain-wordmark colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-rails-plain-wordmark colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-bootstrap-plain-wordmark colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-tailwindcss-plain colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-figma-plain colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <Image src={sql} alt="sql icon" className="h-14 w-14" />
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-heroku-plain-wordmark colored text-5xl"></i>
                  </div>
                  <div className="text-center shadow-lg p-3 rounded-xl my-10 hover:animate-pulse bg-white dark:bg-gray-200">
                    <i className="devicon-git-plain-wordmark colored text-5xl"></i>
                  </div>
                </div>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <h3 className="text-center text-2xl py-2 md:text-3xl dark:text-whitesmoke font-poppins">
                About me
              </h3>
              <hr />
              <p className="text-md py-5 text-gray-800  dark:text-gray-200 max-w-md mx-auto mt-4 font-lora text-lg leading-loose text-center">
                I am pursuing a career change from Accounting to Tech. I
                completed an intensive full-stack web development course at Le
                Wagon in Lisbon, Portugal, which has allowed me to learn and
                practice various new skills, including Ruby, HTML, CSS, and
                Javascript, among many others. I am looking for a collaborative,
                team-focused culture and opportunities to learn and grow my web
                development skills! When I am not coding, I enjoy spending my
                time reading, practicing yoga and traveling whenever possible.
              </p>
            </div>
          </div>
          <h3 className="text-center text-2xl py-2 md:text-3xl dark:text-whitesmoke font-poppins">
            Projects
          </h3>
          <hr />
          <div className="flex flex-col lg:flex-row lg:flex-wrap py-10 gap-10">
            <div className="basis-1/3 flex-1">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-gray-200">
                <Image
                  src={foodvisualizer}
                  alt="project1"
                  className=" hover:animate-pulse"
                />
                <h3 className="text-lg font-medium pt-8 pb-2 font-poppins">
                  Food Visualizer
                </h3>
                <p className="py-2 font-lora">
                  A web application in which restaurant guests can see pictures
                  of the menu dishes before placing an order.
                </p>
                <h4 className="py-4 text-blue font-lora">Ruby on Rails</h4>
                <div className="flex justify-between">
                  <a
                    className="font-lora bg-gradient-to-r from-pink to-blue text-white text-sm p-2 rounded-md hover:brightness-110"
                    target="_blank"
                    rel="noreferrer"
                    href="http://www.foodvisualizer.com/"
                  >
                    View Live
                  </a>
                  <a
                    className="font-lora p-1 bg-gradient-to-tr from-blue to-pink rounded-md hover:brightness-110"
                    target="_blank"
                    rel="noreferrer"
                    href="https://github.com/amandaroj/FoodVisualizer"
                  >
                    <div className="bg-white rounded-md p-1 text-gray-500 text-sm">
                      Source Code
                    </div>
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-gray-200 ">
                <Image
                  src={campers}
                  alt="project1"
                  className="object-cover hover:animate-pulse"
                />
                <h3 className="text-lg font-medium pt-8 pb-2 font-poppins">
                  Campers Rental
                </h3>
                <p className="py-2 font-lora">
                  A clone of Airbnb built from scratch in five days along with
                  three other aspiring web developers.{" "}
                </p>
                <h4 className="py-4 text-blue font-lora">Ruby on Rails</h4>
                <div className="flex justify-between">
                  <a
                    className="font-lora bg-gradient-to-r from-pink to-blue text-white text-sm p-2 rounded-md hover:brightness-110"
                    target="_blank"
                    rel="noreferrer"
                    href="https://camper-rental.herokuapp.com/"
                  >
                    View Live
                  </a>
                  <a
                    className="font-lora p-1 bg-gradient-to-tr from-blue to-pink rounded-md hover:brightness-110"
                    target="_blank"
                    rel="noreferrer"
                    href="https://github.com/EvaHaverkort/camper-rental"
                  >
                    <div className="bg-white rounded-md p-1 text-gray-500 text-sm">
                      Source Code
                    </div>
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-gray-200 ">
                <Image
                  src={calc}
                  alt="project1"
                  width={500}
                  height={500}
                  layout="responsive"
                  className="object-cover hover:animate-pulse"
                />
                <h3 className="font-poppins text-lg font-medium pt-8 pb-2">
                  Calculator App
                </h3>
                <p className="font-lora py-2">
                  A simple calculator which can perform basic arithmetic
                  operations depending upon the user input.
                </p>
                <h4 className="font-lora py-4 text-blue">Javascript</h4>
                <div className="flex justify-between">
                  <a
                    className="font-lora bg-gradient-to-r from-pink to-blue text-white text-sm p-2 rounded-md hover:brightness-110"
                    target="_blank"
                    rel="noreferrer"
                    href="https://amandaroj.github.io/calculator-app/"
                  >
                    View Live
                  </a>
                  <a
                    className="font-lora p-1 bg-gradient-to-tr from-blue to-pink rounded-md hover:brightness-110"
                    target="_blank"
                    rel="noreferrer"
                    href="https://github.com/amandaroj/calculator-app"
                  >
                    <div className="bg-white rounded-md p-1 text-gray-500 text-sm">
                      Source Code
                    </div>
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-gray-200">
                <Image
                  src={quote}
                  alt="project1"
                  width={500}
                  height={500}
                  layout="responsive"
                  className="object-cover hover:animate-pulse"
                />
                <h3 className="text-lg font-medium pt-8 pb-2 font-poppins">
                  Quote Generator
                </h3>
                <p className="font-lora py-2">
                  {" "}
                  An app that fetches a new random quote using an API each time
                  a button is pressed and displays it in the browser.
                </p>
                <h4 className="font-lora py-4 text-blue">Javascript</h4>
                <div className="flex justify-between">
                  <a
                    className="font-lora bg-gradient-to-r from-pink to-blue text-white text-sm p-2 rounded-md hover:brightness-110"
                    target="_blank"
                    rel="noreferrer"
                    href=" https://amandaroj.github.io/quote-generator/"
                  >
                    View Live
                  </a>
                  <a
                    className="font-lora p-1 bg-gradient-to-tr from-blue to-pink rounded-md hover:brightness-110"
                    target="_blank"
                    rel="noreferrer"
                    href="https://github.com/amandaroj/quote-generator"
                  >
                    <div className="bg-white rounded-md p-1 text-gray-500 text-sm">
                      Source Code
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <hr />

          <div className="bg-white text-gray-600 shadow-lg p-5 rounded-xl mt-20 mx-auto md:max-w-2xl dark:bg-gray-200">
            <h3
              id="contact"
              className="text-3xl py-1 text-center text-gray-700 mb-8 divide-black font-poppins"
            >
              Get In Touch
            </h3>
            <form
              action="https://formsubmit.co/rojteramanda@gmail.com"
              method="POST"
              className="flex flex-col space-y-4 "
            >
              <div>
                <label for="" className="text-sm font-lora">
                  Your Name
                </label>
                <input
                  type="text"
                  name="name"
                  className="ring-1 ring-gray-300 w-full rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-blue"
                  required
                />
              </div>
              <div>
                <label for="" className="text-sm font-lora">
                  E-mail
                </label>
                <input
                  type="email"
                  name="email"
                  className="ring-1 ring-gray-300 w-full rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-blue"
                  required
                />
              </div>
              <div>
                <label for="" className="text-sm font-lora">
                  Message
                </label>
                <textarea
                  type="message"
                  name="message"
                  placeholder="..."
                  rows={6}
                  className="font-lora ring-1 ring-gray-300 w-full rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-blue"
                ></textarea>
              </div>
              <button
                className="font-lora inline-block self-end w-20 text-center bg-gradient-to-r from-pink to-blue text-white text-sm p-2 rounded-md hover:brightness-110"
                type="submit"
              >
                Send
              </button>
            </form>
          </div>
          <footer className="h-20"></footer>
        </section>
      </main>
    </div>
  );
}
